language: ruby
dist: trusty
script: bundle exec rake test

matrix:
  include:
  - os: linux
    rvm: 2.4.4
  - os: osx
    rvm: 2.4.4
  - os: linux
    rvm: 2.5.1
  - os: osx
    rvm: 2.5.1
  - os: linux
    rvm: 2.6.6
  - os: osx
    rvm: 2.6.6
  - os: linux
    rvm: 2.7.1
  - os: osx
    rvm: 2.7.1
  fast_finish: true
